### ISSUE TITLE
meaning of each row in 2d landmark

### ISSUE THREAD

**Issue by betterze** [qq775193759/3D-CariGAN#1]
Dear 3D-CariGAN team,

Thank you for sharing this great work with us, I really like it.

In the cari_2D_dataset.zip landmarks, each txt file contains two columns index. They are the index of each face landmark, right? Could you tell me which part of the face each row represent? Or which format the txt file follow? So I can understand the meaning of each row by myself.

Thank you for your help.

Best Wishes,

Alex

**Comment by qq775193759** [comment]
The .txt file contains 68 rows and each rows has two elements (x and y). They are 68 2D facial landmarks.

**Comment by betterze** [comment]
Thx a lot.
